version: "3.8"

services:
  db:
    image: postgres:16.2-alpine
    container_name: rudex_postgres_db
    restart: always
    environment:
      POSTGRES_USER: rudex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rudex_dev
    ports:
      - "4020:5432"
    volumes:
      - pgdata_rudex_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rudex_redis
    restart: always
    ports:
      - "4030:6379"
    volumes:
      - redis_rudex_dev:/data

  mailhog:
    image: mailhog/mailhog
    container_name: rudex_mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata_rudex_dev:
  redis_rudex_dev:
