/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migration_time: Timestamp | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  is_locked: number | null;
}

export interface Registrations {
  confirmation_token: string;
  confirmation_token_expires_at: Timestamp;
  created_at: Timestamp;
  email: string;
  id: Generated<string>;
  password: string;
  username: string;
}

export interface Users {
  access_token: string | null;
  access_token_expiry_date: Timestamp | null;
  created_at: Timestamp;
  email: string;
  google_user_id: string | null;
  google_user_name: string | null;
  id: Generated<string>;
  password: string | null;
  refresh_token: string | null;
  updated_at: Timestamp;
  username: string;
}

export interface DB {
  knex_migrations: KnexMigrations;
  knex_migrations_lock: KnexMigrationsLock;
  registrations: Registrations;
  users: Users;
}
